# Preprocessing

In [2]:
import tensorflow as tf

import torch
import torch.nn as nn
import torch.nn.functional as F

from sklearn.model_selection import train_test_split

In [3]:
import pandas as pd
import numpy as np

In [4]:
reviews = pd.read_csv("../cleaned_text.csv")

In [5]:
score = []
for i in range(1000):
    score.append(1)
for i in range(1000):
    score.append(0)
reviews['Score'] = score

In [6]:
reviews

Unnamed: 0                                       cleaned_text  Score
0              0  film adapt comic book plenty success whether s...      1
1              1  every movie come along suspect studio every in...      1
2              2  get mail work alot good deserve order make fil...      1
3              3  jaw rare film grab attention show single image...      1
4              4  moviemaking lot like general manager nfl team ...      1
...          ...                                                ...    ...
1995        1995  anything stigmata take warning release film re...      0
1996        1996  john boorman zardoz goofy cinematic debacle fu...      0
1997        1997  kid hall acquired taste take least season watc...      0
1998        1998  time john carpenter great horror director cour...      0
1999        1999  two party guy bob head haddaway dance hit love...      0

[2000 rows x 3 columns]

In [7]:
vocab = []
for i in reviews.iloc[:,1]:
    vocab += i.split(' ')
vocab

['film',
 'adapt',
 'comic',
 'book',
 'plenty',
 'success',
 'whether',
 'superheroes',
 'batman',
 'superman',
 'spawn',
 'gear',
 'toward',
 'kid',
 'casper',
 'arthouse',
 'crowd',
 'ghost',
 'world',
 'there',
 'never',
 'really',
 'comic',
 'book',
 'like',
 'hell',
 'starter',
 'create',
 'alan',
 'moore',
 'eddie',
 'campbell',
 'bring',
 'medium',
 'whole',
 'new',
 'level',
 'mid',
 'series',
 'call',
 'watchman',
 'say',
 'moore',
 'campbell',
 'thoroughly',
 'research',
 'subject',
 'jack',
 'ripper',
 'would',
 'like',
 'say',
 'michael',
 'jackson',
 'start',
 'look',
 'little',
 'odd',
 'book',
 'graphic',
 'novel',
 'over',
 'page',
 'long',
 'include',
 'nearly',
 'consist',
 'nothing',
 'footnote',
 'word',
 'dismiss',
 'film',
 'source',
 'can',
 'get',
 'past',
 'whole',
 'comic',
 'book',
 'thing',
 'you',
 'might',
 'find',
 'another',
 'stumble',
 'block',
 'hell',
 'director',
 'albert',
 'allen',
 'hughes',
 'hughes',
 'brother',
 'direct',
 'seem',
 'almost',


In [8]:
vocab = np.array(vocab)
vocab = np.unique(vocab)

In [9]:
vocab

array(['a', 'aa', 'aaa', ..., 'zwick', 'zwigoff', 'zycie'], dtype='<U25')

In [10]:
num = 1
dic = {}
for i in vocab:
    dic.update({i:num})
    num += 1

In [11]:
dic

{'a': 1,
 'aa': 2,
 'aaa': 3,
 'aaaaaah': 4,
 'aaaahhhs': 5,
 'aahs': 6,
 'aaliyah': 7,
 'aalyah': 8,
 'aamir': 9,
 'aardman': 10,
 'aaron': 11,
 'aatish': 12,
 'ab': 13,
 'aback': 14,
 'abandon': 15,
 'abandoned': 16,
 'abandonment': 17,
 'abate': 18,
 'abba': 19,
 'abbe': 20,
 'abberation': 21,
 'abberline': 22,
 'abbot': 23,
 'abbott': 24,
 'abbotts': 25,
 'abbreviated': 26,
 'abby': 27,
 'abc': 28,
 'abdomen': 29,
 'abduct': 30,
 'abducted': 31,
 'abductees': 32,
 'abduction': 33,
 'abe': 34,
 'abel': 35,
 'aberdeen': 36,
 'aberration': 37,
 'abet': 38,
 'abeyance': 39,
 'abhorrence': 40,
 'abhorrent': 41,
 'abider': 42,
 'abides': 43,
 'abigail': 44,
 'abiility': 45,
 'ability': 46,
 'abit': 47,
 'abject': 48,
 'ablaze': 49,
 'able': 50,
 'ably': 51,
 'abnormal': 52,
 'abnormally': 53,
 'aboard': 54,
 'abode': 55,
 'abolish': 56,
 'abolitionist': 57,
 'abominable': 58,
 'abomination': 59,
 'aborbed': 60,
 'aborginal': 61,
 'aboriginal': 62,
 'aborigine': 63,
 'abort': 64,
 'aborte

In [12]:
new = []
for i in reviews.iloc[:,1]:
    xyz = i.split(' ')
    row = []
    for j in xyz:
        row.append(dic[j])
    new.append(row)

In [13]:
this = []
for i in range(2000):
    this.append(i)
score = np.array(score)
d = {'Reviewings': new, 'Score': score}
review_num = pd.DataFrame(data=d)

In [14]:
review_num

Reviewings  Score
0     [9942, 277, 5148, 3019, 20919, 26774, 30552, 2...      1
1     [9148, 18175, 5130, 712, 27034, 26633, 9148, 1...      1
2     [11084, 16627, 30916, 716, 11398, 7000, 19476,...      1
3     [14514, 22264, 9942, 11486, 1631, 24951, 25162...      1
4     [18181, 16294, 15972, 10982, 16714, 18717, 274...      1
...                                                 ...    ...
1995  [1120, 26383, 27288, 30290, 22731, 9942, 22724...      0
1996  [14694, 3042, 31258, 11424, 4691, 6587, 10708,...      0
1997  [15097, 11978, 223, 27409, 27288, 15688, 24398...      0
1998  [27986, 14694, 4041, 11595, 12888, 7326, 5887,...      0
1999  [28718, 20124, 11889, 2919, 12272, 11932, 6420...      0

[2000 rows x 2 columns]

In [30]:
x_train, x_val, y_train, y_val = train_test_split(review_num.iloc[:,0],
                                                      review_num.iloc[:,1],
                                                      test_size = 0.2, random_state=73)

In [31]:
y_train = np.array(y_train)
y_val = np.array(y_val)
x_train = np.array(x_train)
x_val = np.array(x_val)

In [35]:
pad_sequences(np.array(x_train), maxlen=max_length, padding='post')

array([[ 9148, 31104, 12741, ...,     0,     0,     0],
       [30931, 15488, 28147, ...,     0,     0,     0],
       [ 3850, 12649,  2818, ..., 19361, 14859,  8711],
       ...,
       [30295,  2262,  7175, ...,     0,     0,     0],
       [26387, 30361, 15262, ...,  1570, 27696, 18175],
       [31024,  8247, 16294, ...,     0,     0,     0]])

In [40]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

max_length = 1000
x_train = pad_sequences(np.asarray(x_train), maxlen=max_length, padding='post')
x_val = pad_sequences(np.asarray(x_val), maxlen=max_length, padding='post')

In [43]:
y_train[0]

1

In [46]:
from tensorflow.keras.layers import Dense, Embedding,GlobalMaxPooling1D, Conv1D, Flatten
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Embedding

vocab_size = 1600
max_length = 1000

model = Sequential([
    Embedding(vocab_size, 8, input_length=max_length),
   Conv1D(128, 5, activation='relu'),
    GlobalMaxPooling1D(),
  Dense(10, activation='relu'),
  Flatten(),
  Dense(1, activation='sigmoid'),
  
])
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
history = model.fit(x_train, y_train, epochs=20, validation_data=(x_val, y_val))


Epoch 1/20


InvalidArgumentError: Graph execution error:

Detected at node 'sequential_3/embedding_5/embedding_lookup' defined at (most recent call last):
    File "C:\Users\gouth\anaconda3\lib\runpy.py", line 194, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "C:\Users\gouth\anaconda3\lib\runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "C:\Users\gouth\anaconda3\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
      app.launch_new_instance()
    File "C:\Users\gouth\anaconda3\lib\site-packages\traitlets\config\application.py", line 845, in launch_instance
      app.start()
    File "C:\Users\gouth\anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 612, in start
      self.io_loop.start()
    File "C:\Users\gouth\anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 149, in start
      self.asyncio_loop.run_forever()
    File "C:\Users\gouth\anaconda3\lib\asyncio\base_events.py", line 570, in run_forever
      self._run_once()
    File "C:\Users\gouth\anaconda3\lib\asyncio\base_events.py", line 1859, in _run_once
      handle._run()
    File "C:\Users\gouth\anaconda3\lib\asyncio\events.py", line 81, in _run
      self._context.run(self._callback, *self._args)
    File "C:\Users\gouth\anaconda3\lib\site-packages\tornado\ioloop.py", line 690, in <lambda>
      lambda f: self._run_callback(functools.partial(callback, future))
    File "C:\Users\gouth\anaconda3\lib\site-packages\tornado\ioloop.py", line 743, in _run_callback
      ret = callback()
    File "C:\Users\gouth\anaconda3\lib\site-packages\tornado\gen.py", line 787, in inner
      self.run()
    File "C:\Users\gouth\anaconda3\lib\site-packages\tornado\gen.py", line 748, in run
      yielded = self.gen.send(value)
    File "C:\Users\gouth\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 365, in process_one
      yield gen.maybe_future(dispatch(*args))
    File "C:\Users\gouth\anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
      yielded = next(result)
    File "C:\Users\gouth\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 268, in dispatch_shell
      yield gen.maybe_future(handler(stream, idents, msg))
    File "C:\Users\gouth\anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
      yielded = next(result)
    File "C:\Users\gouth\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 543, in execute_request
      self.do_execute(
    File "C:\Users\gouth\anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
      yielded = next(result)
    File "C:\Users\gouth\anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 306, in do_execute
      res = shell.run_cell(code, store_history=store_history, silent=silent)
    File "C:\Users\gouth\anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 536, in run_cell
      return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
    File "C:\Users\gouth\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2877, in run_cell
      result = self._run_cell(
    File "C:\Users\gouth\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2923, in _run_cell
      return runner(coro)
    File "C:\Users\gouth\anaconda3\lib\site-packages\IPython\core\async_helpers.py", line 68, in _pseudo_sync_runner
      coro.send(None)
    File "C:\Users\gouth\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3146, in run_cell_async
      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
    File "C:\Users\gouth\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3338, in run_ast_nodes
      if (await self.run_code(code, result,  async_=asy)):
    File "C:\Users\gouth\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3418, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "<ipython-input-46-662532357a46>", line 18, in <module>
      history = model.fit(x_train, y_train, epochs=20, validation_data=(x_val, y_val))
    File "C:\Users\gouth\anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\gouth\anaconda3\lib\site-packages\keras\engine\training.py", line 1384, in fit
      tmp_logs = self.train_function(iterator)
    File "C:\Users\gouth\anaconda3\lib\site-packages\keras\engine\training.py", line 1021, in train_function
      return step_function(self, iterator)
    File "C:\Users\gouth\anaconda3\lib\site-packages\keras\engine\training.py", line 1010, in step_function
      outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\gouth\anaconda3\lib\site-packages\keras\engine\training.py", line 1000, in run_step
      outputs = model.train_step(data)
    File "C:\Users\gouth\anaconda3\lib\site-packages\keras\engine\training.py", line 859, in train_step
      y_pred = self(x, training=True)
    File "C:\Users\gouth\anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\gouth\anaconda3\lib\site-packages\keras\engine\base_layer.py", line 1096, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "C:\Users\gouth\anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 92, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\gouth\anaconda3\lib\site-packages\keras\engine\sequential.py", line 374, in call
      return super(Sequential, self).call(inputs, training=training, mask=mask)
    File "C:\Users\gouth\anaconda3\lib\site-packages\keras\engine\functional.py", line 451, in call
      return self._run_internal_graph(
    File "C:\Users\gouth\anaconda3\lib\site-packages\keras\engine\functional.py", line 589, in _run_internal_graph
      outputs = node.layer(*args, **kwargs)
    File "C:\Users\gouth\anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 64, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\gouth\anaconda3\lib\site-packages\keras\engine\base_layer.py", line 1096, in __call__
      outputs = call_fn(inputs, *args, **kwargs)
    File "C:\Users\gouth\anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 92, in error_handler
      return fn(*args, **kwargs)
    File "C:\Users\gouth\anaconda3\lib\site-packages\keras\layers\embeddings.py", line 197, in call
      out = tf.nn.embedding_lookup(self.embeddings, inputs)
Node: 'sequential_3/embedding_5/embedding_lookup'
indices[30,0] = 10354 is not in [0, 1600)
	 [[{{node sequential_3/embedding_5/embedding_lookup}}]] [Op:__inference_train_function_2686]

In [362]:
x_train.shape

(1600,)

In [317]:
batch_size = 100

x_train = [torch.tensor(x) for x in x_train]
X_train = nn.utils.rnn.pad_sequence(x_train, batch_first=True, padding_value=0).long()
X_train = X_train.view(-1, batch_size, X_train.shape[1])


In [318]:
len_voc = int((X_train.max()+1).item())

x_val = [torch.tensor(x) for x in x_val]
X_val = nn.utils.rnn.pad_sequence(x_val, batch_first=True, padding_value=0).long()
X_val = X_val.view(-1, batch_size, X_val.shape[1])

y_train = torch.tensor(y_train).view(-1, batch_size)
y_val = torch.tensor(y_val).view(-1, batch_size)

# CNN

In [319]:
from keras.models import Sequential
from keras import layers
import tensorflow as tf
from tensorflow.keras.layers import Flatten

x_train = tf.convert_to_tensor(X_train, tf.float32)
x_val = tf.convert_to_tensor(X_val, tf.float32)
y_train = tf.cast(y_train, tf.float32)
y_train = tf.convert_to_tensor(y_train)
y_val = tf.cast(y_val, tf.float32)
y_val = tf.convert_to_tensor(y_val)


In [340]:
from tensorflow.keras.layers import Dense, Embedding,GlobalMaxPooling1D, Conv1D
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Embedding

model = Sequential([
    Embedding(5000, 8, input_length=100),
   Conv1D(128, 5, activation='relu'),
    GlobalMaxPooling1D(),
  Dense(10, activation='relu'),
  Dense(1, activation='sigmoid')
])
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
history = model.fit(x_train, y_train, epochs=20, validation_data=(x_val, y_val))
loss, accuracy = model.evaluate(x_val,y_val)
print('Testing Accuracy is {} '.format(accuracy*100))


Epoch 1/20


ValueError: in user code:

    File "C:\Users\gouth\anaconda3\lib\site-packages\keras\engine\training.py", line 1021, in train_function  *
        return step_function(self, iterator)
    File "C:\Users\gouth\anaconda3\lib\site-packages\keras\engine\training.py", line 1010, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\gouth\anaconda3\lib\site-packages\keras\engine\training.py", line 1000, in run_step  **
        outputs = model.train_step(data)
    File "C:\Users\gouth\anaconda3\lib\site-packages\keras\engine\training.py", line 859, in train_step
        y_pred = self(x, training=True)
    File "C:\Users\gouth\anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "C:\Users\gouth\anaconda3\lib\site-packages\keras\engine\input_spec.py", line 214, in assert_input_compatibility
        raise ValueError(f'Input {input_index} of layer "{layer_name}" '

    ValueError: Exception encountered when calling layer "sequential_42" (type Sequential).
    
    Input 0 of layer "global_max_pooling1d_38" is incompatible with the layer: expected ndim=3, found ndim=4. Full shape received: (None, 100, 1566, 128)
    
    Call arguments received:
      • inputs=tf.Tensor(shape=(None, 100, 1570), dtype=float32)
      • training=True
      • mask=None


In [326]:
x_train.shape

TensorShape([16, 100, 1570])

In [327]:
y_train.shape

(16, 100)

In [328]:
x_val.shape

TensorShape([4, 100, 1144])

In [329]:
y_val.shape

(4, 100)

In [334]:
y_train = np.asarray(y_train).astype('float32').reshape((-1,batch_size))
y_val = np.asarray(y_val).astype('float32').reshape((-1,batch_size))


ValueError: Exception encountered when calling layer "sequential_41" (type Sequential).

Input 0 of layer "conv1d_36" is incompatible with the layer: expected min_ndim=3, found ndim=2. Full shape received: (100, 1570)

Call arguments received:
  • inputs=tf.Tensor(shape=(100, 1570), dtype=float32)
  • training=None
  • mask=None

In [341]:

embedding_dim = 100

model = Sequential()
model.add(layers.Conv1D(128, 5, activation='relu'))
model.add(layers.GlobalMaxPooling1D())
model.add(layers.Dense(10, activation='relu'))
model.add(layers.Dense(1, activation='sigmoid'))
#model.add(Flatten())
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])
history = model.fit(x_train, y_train,
                    epochs=100,
                    validation_data=(x_val, y_val),
                    batch_size=100)

Epoch 1/100


ValueError: in user code:

    File "C:\Users\gouth\anaconda3\lib\site-packages\keras\engine\training.py", line 1021, in train_function  *
        return step_function(self, iterator)
    File "C:\Users\gouth\anaconda3\lib\site-packages\keras\engine\training.py", line 1010, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\gouth\anaconda3\lib\site-packages\keras\engine\training.py", line 1000, in run_step  **
        outputs = model.train_step(data)
    File "C:\Users\gouth\anaconda3\lib\site-packages\keras\engine\training.py", line 860, in train_step
        loss = self.compute_loss(x, y, y_pred, sample_weight)
    File "C:\Users\gouth\anaconda3\lib\site-packages\keras\engine\training.py", line 918, in compute_loss
        return self.compiled_loss(
    File "C:\Users\gouth\anaconda3\lib\site-packages\keras\engine\compile_utils.py", line 201, in __call__
        loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    File "C:\Users\gouth\anaconda3\lib\site-packages\keras\losses.py", line 141, in __call__
        losses = call_fn(y_true, y_pred)
    File "C:\Users\gouth\anaconda3\lib\site-packages\keras\losses.py", line 245, in call  **
        return ag_fn(y_true, y_pred, **self._fn_kwargs)
    File "C:\Users\gouth\anaconda3\lib\site-packages\keras\losses.py", line 1932, in binary_crossentropy
        backend.binary_crossentropy(y_true, y_pred, from_logits=from_logits),
    File "C:\Users\gouth\anaconda3\lib\site-packages\keras\backend.py", line 5247, in binary_crossentropy
        return tf.nn.sigmoid_cross_entropy_with_logits(labels=target, logits=output)

    ValueError: `logits` and `labels` must have the same shape, received ((None, 1) vs (None, 100)).


In [296]:
x_train[2]

<tf.Tensor: shape=(100, 1570), dtype=float32, numpy=
array([[29598.,  2818.,  5130., ...,     0.,     0.,     0.],
       [ 4997.,  3428.,  1845., ...,     0.,     0.,     0.],
       [22770.,   637., 12662., ...,     0.,     0.,     0.],
       ...,
       [  814., 16322.,  5646., ...,     0.,     0.,     0.],
       [27982., 23407., 16931., ...,     0.,     0.,     0.],
       [ 3955., 15821.,  9197., ...,     0.,     0.,     0.]],
      dtype=float32)>

In [342]:
import torch
import torch.nn.functional as F
import torch.nn as nn
import torch.optim as optim

# Create word embedding from scratch
embeddings = nn.Embedding(len_voc, 100)

# Build CNN model
class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.embeddings = nn.Embedding(len_voc, 100)
        self.cnn = nn.Conv2d(1, 100, (3, 100))
        self.clf = nn.Linear(100, 2)

    def forward(self, x):
        # Add word embeddings
        x = self.embeddings(x)
        # Add an extra dimension for CNN
        x = x.unsqueeze(1)
        # Apply CNN
        x = self.cnn(x)
        # Choose the maximum value of each filter and delete the extra dimension
        x = x.max(2)[0].squeeze(2)
        # Choose the most important features for the classification
        x = F.relu(x) 
        #  Apply linear nn for classification
        x = self.clf(x)
        # Return the probability of positive and negative
        return F.softmax(x, 1)

# Use GPU for the model      
model = Model()
# opmization function
optimizer = optim.Adam(model.parameters(), lr=1e-3)
# calculate the loss
criterio  = nn.CrossEntropyLoss()


In [343]:

from sklearn import metrics

# Function for evaluating
def get_f1(X, y_real):
  y_pred = []
  for x in X:
      # Choose the value with higher probability
      y_pred.append(model(x.cuda()).argmax(1).cpu().detach())
  y_pred = torch.cat(y_pred)
  return metrics.f1_score(y_true=y_real, y_pred=y_pred)

# Training steps
epochs = 20
LOSS = []
for e in range(epochs):
    for i, (x, y) in enumerate(zip(x_train, y_train)):
        
        # Delete the prvious values of the gradient
        optimizer.zero_grad()
        
        y_pred = model(tf.constant(x))
        loss = criterio(y_pred, y)

        # Compute the gradient
        loss.backward()

        # Apply the optimization method for one step
        optimizer.step()
        
        LOSS.append(loss.item())
        if i%200==0:
            with torch.no_grad():
                f1 = get_f1(X_val, y_val)
            print('Epoch: %d \t Batch: %d \t Loss: %.10f \t F1_val: %.10f'%(e,i, torch.tensor(LOSS[-100:]).mean(), f1))

TypeError: embedding(): argument 'indices' (position 2) must be Tensor, not tensorflow.python.framework.ops.EagerTensor

In [344]:

# Training steps
epochs = 20
LOSS = []
for e in range(epochs):
    for i, (x, y) in enumerate(zip(x_train, y_train)):
        
        # Delete the prvious values of the gradient
        optimizer.zero_grad()
        
        y_pred = model(tf.Tensor(x, dtype='float32', value_index=batch_size))
        loss = criterio(y_pred, y)

        # Compute the gradient
        loss.backward()

        # Apply the optimization method for one step
        optimizer.step()
        
        LOSS.append(loss.item())
        if i%200==0:
            with torch.no_grad():
                f1 = get_f1(X_val, y_val)
            print('Epoch: %d \t Batch: %d \t Loss: %.10f \t F1_val: %.10f'%(e,i, torch.tensor(LOSS[-100:]).mean(), f1))

TypeError: op needs to be an Operation: tf.Tensor(
[[ 9148. 31104. 12741. ...     0.     0.     0.]
 [30931. 15488. 28147. ...     0.     0.     0.]
 [30995.  6896.  9773. ...     0.     0.     0.]
 ...
 [ 8354. 24941. 15262. ...     0.     0.     0.]
 [12932. 25142. 23111. ...     0.     0.     0.]
 [14636. 12464. 20130. ...     0.     0.     0.]], shape=(100, 1570), dtype=float32)

In [345]:
from sklearn import metrics

# Function for evaluating
def get_f1(X, y_real):
  y_pred = []
  for x in X:
      # Choose the value with higher probability
      y_pred.append(model(x).argmax(1).cpu().detach())
  y_pred = torch.cat(y_pred)
  return metrics.f1_score(y_true=y_real, y_pred=y_pred)

In [346]:

# Training steps
epochs = 1000
LOSS = []
for e in range(epochs):
    for i, (x, y) in enumerate(zip(x_train, y_train)):
        
        # Delete the prvious values of the gradient
        optimizer.zero_grad()
        
        y_pred = model(x)
        loss = criterio(y_pred, y)

        # Compute the gradient
        loss.backward()

        # Apply the optimization method for one step
        optimizer.step()
        
        LOSS.append(loss.item())
        if i%200==0:
            with torch.no_grad():
                f1 = get_f1(x_val, y_val)
            print('Epoch: %d \t Batch: %d \t Loss: %.10f \t F1_val: %.10f'%(e,i, torch.tensor(LOSS[-100:]).mean(), f1))

TypeError: embedding(): argument 'indices' (position 2) must be Tensor, not tensorflow.python.framework.ops.EagerTensor

In [347]:
model(x_train[0])

TypeError: embedding(): argument 'indices' (position 2) must be Tensor, not tensorflow.python.framework.ops.EagerTensor